name: Build Kivy iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install macOS dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config ios-deploy

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install kivy==2.3.0 buildozer==1.5.0 Cython pbxproj packaging

      - name: Clone and build Kivy iOS toolchain
        run: |
          git clone https://github.com/kivy/kivy-ios
          cd kivy-ios
          python toolchain.py build python3 kivy

      - name: Prepare iOS platform
        run: |
          buildozer init || true
          buildozer ios clean
          buildozer ios platform update

      - name: Build iOS app (debug)
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: |
          buildozer ios debug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: bin/
